### Crear un lote nuevo
POST http://localhost:3000/lotes
Content-Type: application/json

{
    "vacuna": 4,
    "cantidad": 0,
    "deposito": 2
}

### Crear un sublote nuevo
POST http://localhost:3000/sublotes
Content-Type: application/json

{
    "provincia": 2,
    "cantidad": 200,
    "lote": "be6817d9-6960-48b9-afaa-e4fb74112a58"
}

### Crear un minilote nuevo
POST http://localhost:3000/minilotes
Content-Type: application/json

{
    "sublote": "0e424fea-9094-4efb-9830-98dd1909bd60",
    "cantidad": 50,
    "centro": 2
}

### redistribuir un minilote
POST http://localhost:3000/minilotes/redistribuir
Content-Type: application/json

{
    "distribucion": 1,
    "cantidad": 10,
    "minilote": "95a51594-c67a-47c0-873a-6a4a5e582ff4",
    "centroOrigen": 1,
    "centroDestino": 3
}

### descartar un lote
POST http://localhost:3000/lotes/descartar
Content-Type: application/json

{
    "fecha": "2024-09-24",
    "motivo": "tamo probando",
    "lote": "48f99d17-0b09-4b0c-8d1e-75d948ed8b20",
    "formaDescarte": "INCINERACION"
}

### descartar un sublote
POST http://localhost:3000/sublotes/descartar
Content-Type: application/json

{
    "fecha": "2024-09-23",
    "motivo": "tamo probando el descarte de sublotes",
    "sublote": "0e424fea-9094-4efb-9830-98dd1909bd60",
    "formaDescarte": "OTRO"
}

### descartar una distribucion provincial
POST http://localhost:3000/minilotes/descartar
Content-Type: application/json

{
    "fecha": "2024-09-23",
    "motivo": "tamo probando el descarte de distribucion provincial",
    "distribucion": 2,
    "formaDescarte": "OTRO"
}

### crear personal
POST http://localhost:3000/personal
Content-Type: application/json

{
    "nombres": "rebertita",
    "apellidos": "titarober",
    "cargo": "ENFERMERO"
}

### crear paciente
POST http://localhost:3000/pacientes
Content-Type: application/json

{
    "dni": "38932073",
    "nombres": "Manuel",
    "apellidos": "Gutierrez",
    "email": "mlgz1995@hotmail.com",
    "telefono": "2364567187",
    "fechaNac": "1995-11-08",
    "genero": "Masculino"
}

### crear vacunacion
POST http://localhost:3000/vacunacion
Content-Type: application/json

{
    "pacienteId": 1,
    "personalId": 16,
    "centroId": 2,
    "miniloteId": "7ef94f24-f61c-497d-ac79-d89e0bae80c1"
}