### Crear un lote nuevo
POST http://localhost:3000/lotes
Content-Type: application/json

{
    "vacuna": 2,
    "cantidad": 12,
    "deposito": 3
}

### Crear un sublote nuevo
POST http://localhost:3000/sublotes
Content-Type: application/json

{
    "provincia": 1,
    "cantidad": 50,
    "lote": "2b4ef9dd-fe50-4469-9ff7-e39233987f45"
}